@baseUrl = http://127.0.0.1:8000
@adminSecret = change-me-demo-secret

GET {{baseUrl}}/
Accept: application/json

###

GET {{baseUrl}}/health
Accept: application/json

###

GET {{baseUrl}}/admin/config/status
Accept: application/json
X-Admin-Secret: {{adminSecret}}
