BEGIN;

CREATE TABLE alembic_version (
    version_num VARCHAR(32) NOT NULL, 
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

-- Running upgrade  -> 20260321_0001

CREATE TABLE raw_ingest_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    source_name VARCHAR(100) NOT NULL, 
    source_job_id VARCHAR(255) NOT NULL, 
    correlation_id VARCHAR(64), 
    ingest_started_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    ingest_completed_at TIMESTAMP WITH TIME ZONE, 
    status VARCHAR(32) DEFAULT 'pending' NOT NULL, 
    record_count INTEGER DEFAULT 0 NOT NULL, 
    raw_storage_uri TEXT, 
    request_metadata JSONB DEFAULT '{}'::jsonb NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    CONSTRAINT pk_raw_ingest_batch PRIMARY KEY (id)
);

CREATE INDEX ix_raw_ingest_batch_source_name ON raw_ingest_batch (source_name);

CREATE UNIQUE INDEX ix_raw_ingest_batch_source_job_id ON raw_ingest_batch (source_job_id);

CREATE TABLE raw_source_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    batch_id BIGINT NOT NULL, 
    source_name VARCHAR(100) NOT NULL, 
    source_record_id VARCHAR(255) NOT NULL, 
    source_record_version VARCHAR(128), 
    source_record_hash VARCHAR(128), 
    raw_payload JSONB NOT NULL, 
    lookup_fields JSONB DEFAULT '{}'::jsonb NOT NULL, 
    observed_at TIMESTAMP WITH TIME ZONE, 
    ingested_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    CONSTRAINT pk_raw_source_record PRIMARY KEY (id), 
    CONSTRAINT fk_raw_source_record_batch_id_raw_ingest_batch FOREIGN KEY(batch_id) REFERENCES raw_ingest_batch (id) ON DELETE CASCADE
);

CREATE INDEX ix_raw_source_record_source_name ON raw_source_record (source_name);

CREATE INDEX ix_raw_source_record_batch_source_record ON raw_source_record (batch_id, source_record_id);

CREATE INDEX ix_raw_source_record_lookup_fields_gin ON raw_source_record USING gin (lookup_fields);

CREATE TABLE indicator (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    canonical_key TEXT NOT NULL, 
    indicator_type VARCHAR(64) NOT NULL, 
    normalized_value TEXT NOT NULL, 
    display_value TEXT, 
    first_seen TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    last_seen TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    confidence SMALLINT, 
    tags TEXT[] DEFAULT '{}'::text[] NOT NULL, 
    lookup_fields JSONB DEFAULT '{}'::jsonb NOT NULL, 
    enrichment JSONB DEFAULT '{}'::jsonb NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    CONSTRAINT pk_indicator PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_indicator_canonical_key ON indicator (canonical_key);

CREATE INDEX ix_indicator_normalized_value ON indicator (normalized_value);

CREATE INDEX ix_indicator_indicator_type ON indicator (indicator_type);

CREATE INDEX ix_indicator_last_seen ON indicator (last_seen);

CREATE UNIQUE INDEX ix_indicator_type_normalized_value ON indicator (indicator_type, normalized_value);

CREATE INDEX ix_indicator_tags_gin ON indicator USING gin (tags);

CREATE INDEX ix_indicator_lookup_fields_gin ON indicator USING gin (lookup_fields);

CREATE TABLE indicator_source_link (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    indicator_id BIGINT NOT NULL, 
    raw_source_record_id BIGINT NOT NULL, 
    link_type VARCHAR(32) DEFAULT 'observed' NOT NULL, 
    confidence SMALLINT, 
    first_seen_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    last_seen_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    source_context JSONB DEFAULT '{}'::jsonb NOT NULL, 
    CONSTRAINT pk_indicator_source_link PRIMARY KEY (id), 
    CONSTRAINT fk_indicator_source_link_indicator_id_indicator FOREIGN KEY(indicator_id) REFERENCES indicator (id) ON DELETE CASCADE, 
    CONSTRAINT fk_indicator_source_link_raw_source_record_id_raw_source_record FOREIGN KEY(raw_source_record_id) REFERENCES raw_source_record (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ix_indicator_source_link_indicator_record ON indicator_source_link (indicator_id, raw_source_record_id);

CREATE TABLE source_checkpoint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    source_name VARCHAR(100) NOT NULL, 
    checkpoint_key VARCHAR(150) NOT NULL, 
    cursor_value JSONB DEFAULT '{}'::jsonb NOT NULL, 
    last_batch_id BIGINT, 
    last_polled_at TIMESTAMP WITH TIME ZONE, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    CONSTRAINT pk_source_checkpoint PRIMARY KEY (id), 
    CONSTRAINT fk_source_checkpoint_last_batch_id_raw_ingest_batch FOREIGN KEY(last_batch_id) REFERENCES raw_ingest_batch (id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX ix_source_checkpoint_source_checkpoint ON source_checkpoint (source_name, checkpoint_key);

CREATE INDEX ix_source_checkpoint_cursor_value_gin ON source_checkpoint USING gin (cursor_value);

CREATE TABLE export_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    source_job_id VARCHAR(255) NOT NULL, 
    correlation_id VARCHAR(64), 
    export_job_name VARCHAR(150) NOT NULL, 
    export_target VARCHAR(150) NOT NULL, 
    exported_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    record_count INTEGER DEFAULT 0 NOT NULL, 
    status VARCHAR(32) DEFAULT 'pending' NOT NULL, 
    filters JSONB DEFAULT '{}'::jsonb NOT NULL, 
    artifact_uri TEXT, 
    CONSTRAINT pk_export_audit PRIMARY KEY (id)
);

CREATE INDEX ix_export_audit_source_job_id ON export_audit (source_job_id);

CREATE INDEX ix_export_audit_exported_at ON export_audit (exported_at);

CREATE INDEX ix_export_audit_filters_gin ON export_audit USING gin (filters);

CREATE TABLE normalization_error (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    batch_id BIGINT, 
    raw_source_record_id BIGINT, 
    source_name VARCHAR(100) NOT NULL, 
    source_job_id VARCHAR(255), 
    correlation_id VARCHAR(64), 
    error_code VARCHAR(100) NOT NULL, 
    error_message TEXT NOT NULL, 
    error_context JSONB DEFAULT '{}'::jsonb NOT NULL, 
    occurred_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    CONSTRAINT pk_normalization_error PRIMARY KEY (id), 
    CONSTRAINT fk_normalization_error_batch_id_raw_ingest_batch FOREIGN KEY(batch_id) REFERENCES raw_ingest_batch (id) ON DELETE SET NULL, 
    CONSTRAINT fk_normalization_error_raw_source_record_id_raw_source_record FOREIGN KEY(raw_source_record_id) REFERENCES raw_source_record (id) ON DELETE SET NULL
);

CREATE INDEX ix_normalization_error_source_name ON normalization_error (source_name);

CREATE INDEX ix_normalization_error_occurred_at ON normalization_error (occurred_at);

CREATE INDEX ix_normalization_error_error_context_gin ON normalization_error USING gin (error_context);

INSERT INTO alembic_version (version_num) VALUES ('20260321_0001') RETURNING alembic_version.version_num;

COMMIT;

